### ISSUE TITLE
Chore: Dependabot PRs Fail because it can't access `AUTH_API_KEY` 😖 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#258]
@dependabot PRs _always_ fail CI because it cannot access the `AUTH_API_KEY` repository secret. ⛔ 
e.g: https://github.com/dwyl/mvp/pull/257
![image](https://user-images.githubusercontent.com/194400/212018818-405d21e7-9813-4adc-a013-ab9b83266a21.png)

https://github.com/dwyl/mvp/actions/runs/3900093230/jobs/6660377686#step:8:1890
![image](https://user-images.githubusercontent.com/194400/212019165-5e4b0905-20ba-4d4c-ae7c-2b860182199b.png)

```sh
  7) test create tag redirects to show when data is valid (AppWeb.TagControllerTest)
Error:      test/app_web/controllers/tag_controller_test.exs:42
     ** (MatchError) no match of right hand side value: nil
     code: |> assign(:jwt, AuthPlug.Token.generate_jwt!(%{id: 1, picture: ""}))
     stacktrace:
       (auth_plug 1.5.1) lib/token.ex:52: AuthPlug.Token.client_secret/0
Warning:        (auth_plug 1.5.1) lib/token.ex:86: AuthPlug.Token.generate_jwt!/1
       test/app_web/controllers/tag_controller_test.exs:45: (test)
```

This has gone on for _waaaay_ too long. So I'm fixing it _now_!

**Comment by nelsonic** [comment]
Let's see if the `auth_plug` @dependabot PRs pass. 🔍

**Comment by nelsonic** [comment]
Yep, they doooo! 🎉  see: https://github.com/dwyl/auth_plug/pull/96
![image](https://user-images.githubusercontent.com/194400/212020985-5ae20d9d-2adf-4078-9123-e95502fbd548.png)

Inspecting how `auth_plug` is doing Env Vars for GitHub Actions. 🔍

**Comment by nelsonic** [comment]
Appears to be the same config:

https://github.com/dwyl/auth_plug/blob/1ac09260244d2c49263e347d460fd96353f300c6/.github/workflows/ci.yml#L30-L33

https://github.com/dwyl/auth_plug/settings/secrets/actions
![image](https://user-images.githubusercontent.com/194400/212021938-d8c8d8a0-01db-4581-8780-060372c748c0.png)

**Comment by nelsonic** [comment]
Buuuuuutttt ... `auth_plug` has these lines of config:

https://github.com/dwyl/auth_plug/blob/1ac09260244d2c49263e347d460fd96353f300c6/config/test.exs#L3-L6

```elixir
config :auth_plug,
  api_key:
    "2PzB7PPnpuLsbWmWtXpGyI+kfSQSQ1zUW2Atz/+8PdZuSEJzHgzGnJWV35nTKRwx/dwylauth.herokuapp.com",
  httpoison_mock: true
```

Which make _all_ the difference. 💭

**Comment by nelsonic** [comment]
Annoyingly `Erlang` doesn't allow us to simply borrow this config from `auth_plug` ...

https://github.com/dwyl/mvp/actions/runs/3900868903/jobs/6662031419#step:8:53
![image](https://user-images.githubusercontent.com/194400/212029464-d90db450-2e17-41c5-8729-a250600cd63e.png)

```sh
ERROR! the application :auth_plug has a different value set for key :httpoison_mock during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was not set
  * Runtime value was set to: true

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile auth_plug --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag



Error: 09:25:52.492 [error] Task #PID<0.27[53](https://github.com/dwyl/mvp/actions/runs/3900868903/jobs/6662031419#step:8:54).0> started from #PID<0.94.0> terminating
Warning: ** (stop) "aborting boot"
    (elixir 1.14.1) Config.Provider.boot/2
Function: &:erlang.apply/2
    Args: [#Function<1.127481437/1 in Mix.Tasks.Compile.All.load_apps/3>, [auth_plug: "/home/runner/work/mvp/mvp/_build/test/lib"]]
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (ErlangError) Erlang error: "aborting boot"
        (elixir 1.14.1) Config.Provider.boot/2

Error: Process completed with exit code 1.
```

**Comment by nelsonic** [comment]
Passing:
![image](https://user-images.githubusercontent.com/194400/212031836-69000b39-e6ca-40a1-87b6-666a0be1e91f.png)

**Comment by nelsonic** [comment]
This _should_ be working now. But we will only know for _sure_ on the next PR. 🤖 
Closing for now to declutter. Will re-open if still an issue. 👌

**Comment by nelsonic** [comment]
Reading: https://danielabaron.me/blog/dependabot-secrets/

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/212853035-7e193e19-984c-49b9-9874-3d3435ea5e56.png)

🙄

**Comment by nelsonic** [comment]
https://github.com/dwyl/mvp/settings/secrets/dependabot
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/194400/212853661-f2b41b69-f392-47a6-98fe-12d5c0fe4cdd.png">
