### ISSUE TITLE
Bug/Chore: Review App Script Failing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/mvp#373]
Sadly, on the most recent PR: https://github.com/dwyl/mvp/pull/354 the Review Apps Script is failing consistently: 

https://github.com/dwyl/mvp/actions/runs/5023363276/jobs/9015775607#step:5:1493

<img width="1209" alt="image" src="https://github.com/dwyl/mvp/assets/194400/1e9e7e47-e6be-4e43-aa04-959df12a21a1">

Appears to be a DB issue:

```sh
ERROR! Config provider Config.Reader failed with:
  ** (RuntimeError) environment variable DATABASE_URL is missing.
  For example: ***HOST/DATABASE
      (stdlib 3.17.2.1) erl_eval.erl:685: :erl_eval.do_apply/6
      (stdlib 3.17.2.1) erl_eval.erl:446: :erl_eval.expr/5
      (stdlib 3.17.2.1) erl_eval.erl:123: :erl_eval.exprs/5
      (elixir 1.14.1) src/elixir.erl:288: :elixir.eval_forms/3
      (elixir 1.14.1) lib/module/parallel_checker.ex:107: Module.ParallelChecker.verify/1
      (elixir 1.14.1) lib/code.ex:422: Code.validated_eval_string/3
      (elixir 1.14.1) lib/config.ex:288: Config.__eval__!/3
      (elixir 1.14.1) lib/config/reader.ex:92: Config.Reader.read!/2
  {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,68,65,84,65,66,65,83,69,95,85,82,76,32,105,115,32,109,105,115,115,105,110,103,46,10,70,111,114,32,101,120,97,109,112,108,101,58,32,101,99,116,111,58,47,47,85,83,69,82,58,80,65,83,83,64,72,79,83,84,47,68,65,84,65,66,65,83,69,10>>},[{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,288}]},{'Elixir.Module.ParallelChecker',verify,1,[{file,"lib/module/parallel_checker.ex"},{line,107}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,422}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,288}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}
  init terminating in do_boot ({,[{erl_eval,do_apply,6,[{_},{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Module.ParallelChecker,verify,1,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})
  Crash dump is being written to: erl_crash.dump...done
  Starting clean up.
  [    2.143961] reboot: Restarting system
  machine restart policy set to 'no', not restarting
Error: release command failed - aborting deployment. error release_command machine 4d89169da07d78 exited with non-zero status of 1
```

Given that the `WebSockets` of Review Apps haven't been working for a `while` ...
and a `LiveView` App is all about `WebSockets`. 
I vote that we _either_: 

1. **Dedicate** the time to ***fixing*** this and **documenting** it comprehensively. 

***OR***

2. **_Temporarily_ Disable** the **`Review App Job`** so that CI stops failing (a false negative for all our Commits/PRs) and revisit this once we have a bit more time. 

@SimonLab / @LuchoTurtle what is your preference? 💭 (Thanks! 🙏)

**Comment by LuchoTurtle** [comment]
I've found this link of someone who had the same issue: https://elixirforum.com/t/clean-deploy-to-fly-io-fails-with-database-url-missing-error/52881

As the error states, it's probably a database issue. But it shouldn't be an issue in the first place, this env should be set by `flyctl`

**Comment by LuchoTurtle** [comment]
I've found this link of a person having the same issue as us: https://elixirforum.com/t/clean-deploy-to-fly-io-fails-with-database-url-missing-error/52881.

It's obviously a database problem that shouldn't happen because `flyctl` should set this env when packaging the app.

**Comment by nelsonic** [comment]
@LuchoTurtle do you think it's fixable in `T1h`? 💭

**Comment by LuchoTurtle** [comment]
@nelsonic Don't disable the Review Script. It is used to create the API requests in the `API Definition` test stage.

**Comment by LuchoTurtle** [comment]
@nelsonic I can try but my experience with Fly.io is a bit limited. I've been researching and there isn't much to go by. From the link I've sent, 

> I had issues where the Postgres DB wasn’t being stood up before the deployment finished.

**Comment by LuchoTurtle** [comment]
Maybe this might be the problem that is halting the database and not allowing `flyctl` to attach the database to the application (which is the step that ultimately sets the `DATABASE_URL`, according to https://fly.io/docs/elixir/getting-started/legacy/#attach-our-app-to-the-database.

<img width="747" alt="image" src="https://github.com/dwyl/mvp/assets/17494745/337b8dd3-8617-4783-9e94-69962e34442c">

This pertains the `mvp-pr-234` from the #234 PR, which is already merged.
Should I delete this?

<img width="888" alt="image" src="https://github.com/dwyl/mvp/assets/17494745/5e13a2ff-10a5-4e86-b70f-a0dd33ebe45d">

**Comment by LuchoTurtle** [comment]
I think it worked, given https://github.com/dwyl/mvp/pull/375 passed.

**Comment by LuchoTurtle** [comment]
<img width="867" alt="image" src="https://github.com/dwyl/mvp/assets/17494745/7278aace-01fa-4b7b-8f82-1efeecba7bfe">

The #375 PR appears to have been deleted, so I assume it does.

**Comment by nelsonic** [comment]
Cool. Thanks. 🙏
